import { ethers } from "ethers";
import { poseidonContract } from "circomlibjs";

/// Deploys the Poseidon(2) hasher to the source chain. The bytecode is
/// generated by circomlibjs so on-chain hashing is identical to the Circom
/// `Poseidon(2)` gadget used in the withdraw circuit (the critical parity that
/// makes a client-side Merkle proof verify on-chain).
///
/// Env: SOURCE_RPC_URL, DEPLOYER_PRIVATE_KEY
async function main() {
  const rpc = required("SOURCE_RPC_URL");
  const pk = required("DEPLOYER_PRIVATE_KEY");

  const provider = new ethers.JsonRpcProvider(rpc);
  const wallet = new ethers.Wallet(pk, provider);

  const abi = poseidonContract.generateABI(2);
  const bytecode = poseidonContract.createCode(2);

  // Force a legacy (type-0) tx at an explicit gas price when GAS_PRICE_WEI is
  // set. EIP-1559 reserves ~2x base fee as maxFeePerGas for the balance check,
  // which makes this large (~2.17M gas) deploy fail on thin testnet balances.
  // A legacy tx reserves exactly gasPrice * gas, so it fits a tight budget.
  const overrides: Record<string, bigint> = {};
  if (process.env.GAS_PRICE_WEI) overrides.gasPrice = BigInt(process.env.GAS_PRICE_WEI);

  const factory = new ethers.ContractFactory(abi, bytecode, wallet);
  const contract = await factory.deploy(overrides);
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log("Poseidon(2) hasher deployed at:", address);
  console.log("export HASHER_ADDRESS=" + address);
}

function required(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(`missing env var ${name}`);
  return v;
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
